const state = {
  lang: localStorage.getItem('bejazz-lang') || 'sl',
  view: 'home',
  admin: false,
  events: JSON.parse(localStorage.getItem('bejazz-events') || 'null') || [
    { date: '18. 10. 2026', title: 'Jesen v treh glasovih', place: 'Ljubljana · Cankarjev dom', time: '19:30', ticket: '#' },
    { date: '07. 11. 2026', title: 'BeJazzy gostuje', place: 'Maribor · Vetrinjski dvor', time: '20:00', ticket: '#' },
    { date: '12. 12. 2026', title: 'Zimski koncert', place: 'Kranj · Khislstein', time: '19:00', ticket: '#' }
  ]
};

const copy = {
  sl: {
    nav: ['O nas', 'Koncerti', 'Mediji', 'Pridruži se', 'Kontakt'], location: 'LJUBLJANA · SLOVENIJA', address: 'Ljubljana, Slovenija', scroll: 'POMIKNI ZA RAZISKOVANJE', galleryOne: 'GLAS<br>V GIBANJU', galleryTwo: 'EN<br>RITEM', galleryThree: 'GLASNO<br>SKUPAJ', country: 'SLOVENIJA',
    heroKicker: 'Slovenska vokalna skupina', heroTitle: 'Glas, ki nas povezuje.', heroText: 'BeJazzy je skupnost različnih glasov, enega ritma in neskončne radovednosti. Srečamo se na odru, da skupaj ustvarimo nekaj, česar sam glas ne zmore.', heroCta: 'Razišči koncerte', secondary: 'Spoznaj BeJazzy',
    next: 'Naslednji nastop', aboutKicker: 'Več kot zbor', aboutTitle: 'Ko se glasovi srečajo, nastane energija.', aboutText: 'Ne iščemo popolnosti v enakosti. Iščemo trenutek, ko se različni glasovi slišijo kot eden — živ, igriv in popolnoma naš.', aboutCta: 'Naša zgodba', eventsKicker: 'V živo', eventsTitle: 'Slišimo se kmalu.', allEvents: 'Vsi koncerti', ticket: 'Vstopnice', mediaKicker: 'Ujemi trenutek', mediaTitle: 'BeJazzy skozi objektiv.', mediaCta: 'Odpri medijsko galerijo', joinKicker: 'Tvoj glas šteje', joinTitle: 'Morda nam manjka prav tvoj glas.', joinText: 'Pojdi z nami na vaje, spoznaj ekipo in začuti, ali je BeJazzy prostor zate.', joinCta: 'Kako se pridružim?', contact: 'Kontakt', footer: 'Glasba je skupni jezik. BeJazzy je naš način, da ga govorimo skupaj.', admin: 'Uredi vsebino', close: 'Zapri admin', save: 'Shrani dogodek', newEvent: 'Nov dogodek', adminTitle: 'Vsebinski studio', adminSub: 'Preprost prostor za urejanje koncertov.', date: 'Datum', eventName: 'Ime dogodka', place: 'Lokacija', time: 'Ura', empty: 'Ni dogodkov.'
  },
  en: {
    nav: ['About', 'Concerts', 'Media', 'Join us', 'Contact'], location: 'LJUBLJANA · SLOVENIA', address: 'Ljubljana, Slovenia', scroll: 'SCROLL TO EXPLORE', galleryOne: 'VOICE<br>IN MOTION', galleryTwo: 'ONE<br>RHYTHM', galleryThree: 'LOUD<br>TOGETHER', country: 'SLOVENIA', ticket: 'Tickets',
    heroKicker: 'Slovenian vocal group', heroTitle: 'A voice that connects us.', heroText: 'BeJazzy is a community of different voices, one pulse and endless curiosity. We meet on stage to create something no single voice could make alone.', heroCta: 'Explore concerts', secondary: 'Meet BeJazzy',
    next: 'Next performance', aboutKicker: 'More than a choir', aboutTitle: 'When voices meet, energy happens.', aboutText: 'We are not looking for perfection in sameness. We are looking for the moment different voices sound like one — alive, playful and completely ours.', aboutCta: 'Our story', eventsKicker: 'Live', eventsTitle: 'Hear us soon.', allEvents: 'All concerts', mediaKicker: 'Catch the moment', mediaTitle: 'BeJazzy through a lens.', mediaCta: 'Open media gallery', joinKicker: 'Your voice matters', joinTitle: 'Maybe your voice is the one we are missing.', joinText: 'Come to a rehearsal, meet the team and feel whether BeJazzy is your kind of place.', joinCta: 'How to join', contact: 'Contact', footer: 'Music is a shared language. BeJazzy is how we speak it together.', admin: 'Edit content', close: 'Close admin', save: 'Save event', newEvent: 'New event', adminTitle: 'Content studio', adminSub: 'A simple space for managing concerts.', date: 'Date', eventName: 'Event name', place: 'Location', time: 'Time', empty: 'No events yet.'
  }
};

function t(key) { return copy[state.lang][key]; }
function render() {
  document.documentElement.lang = state.lang;
  document.title = state.lang === 'sl' ? 'BeJazzy — Glas, ki nas povezuje' : 'BeJazzy — A voice that connects us';
  document.getElementById('app').innerHTML = state.admin ? adminTemplate() : siteTemplate();
  bind();
  document.querySelectorAll('.admin-side .wordmark').forEach(wordmark => { wordmark.innerHTML = '<img class="logo" src="BeJazzy.jpg" alt="BeJazzy" />'; });
}

function siteTemplate() {
  const upcoming = state.events[0];
  return `<header class="topbar"><a class="wordmark" href="#home" data-view="home"><img class="logo" src="BeJazzy.jpg" alt="BeJazzy" /></a><nav>${t('nav').map((item, i) => `<a href="#${['about','events','media','join'][i] || 'contact'}" data-view="${['about','events','media','join'][i] || 'contact'}">${item}</a>`).join('')}</nav><div class="header-actions"><button class="lang" data-lang="${state.lang === 'sl' ? 'en' : 'sl'}">${state.lang === 'sl' ? 'EN' : 'SL'} <span>↗</span></button><button class="menu" aria-label="Menu">☰</button></div></header>
  <main id="home"><section class="hero"><div class="hero-copy"><p class="eyebrow">${t('heroKicker')} <span class="line"></span></p><h1>${t('heroTitle')}</h1><p class="hero-text">${t('heroText')}</p><div class="hero-actions"><a class="button primary" href="#events" data-view="events">${t('heroCta')} <span>↗</span></a><a class="text-link" href="#about" data-view="about">${t('secondary')} <span>↗</span></a></div></div><div class="hero-art"><div class="sound-ring ring-one"></div><div class="sound-ring ring-two"></div><div class="sound-ring ring-three"></div><div class="note-note">♪</div><div class="vertical-label">${t('location')}</div></div><div class="hero-foot"><span>01 — 04</span><span class="scroll-note">${t('scroll')} <i>↓</i></span></div></section>
  <section class="next-event"><div><p class="eyebrow dark">${t('next')}</p><h2>${upcoming.title}</h2><p>${upcoming.date} · ${upcoming.place}</p></div><a class="button outline" href="${upcoming.ticket}" target="_blank">${t('ticket')} <span>↗</span></a></section>
  <section class="about section" id="about"><div class="section-aside"><p class="eyebrow">${t('aboutKicker')}</p><span class="big-number">01</span></div><div class="about-content"><h2>${t('aboutTitle')}</h2><p>${t('aboutText')}</p><a class="text-link" href="#contact" data-view="contact">${t('aboutCta')} <span>↗</span></a></div><div class="about-visual"><div class="visual-card"><span>BE</span><strong>JAZ<br>ZY</strong><small>EST. 2014 · ${t('country')}</small></div></div></section>
  <section class="events section" id="events"><div class="section-heading"><div><p class="eyebrow">${t('eventsKicker')}</p><h2>${t('eventsTitle')}</h2></div><a class="text-link" href="#events">${t('allEvents')} <span>↗</span></a></div><div class="event-list">${state.events.map((event, i) => `<article class="event-row"><span class="event-index">0${i+1}</span><span class="event-date">${event.date}</span><div class="event-main"><h3>${event.title}</h3><p>${event.place}</p></div><span class="event-time">${event.time}</span><a class="arrow-link" href="${event.ticket}" target="_blank" aria-label="${t('ticket')}">↗</a></article>`).join('')}</div></section>
  <section class="media section" id="media"><div class="media-copy"><p class="eyebrow">${t('mediaKicker')}</p><h2>${t('mediaTitle')}</h2><a class="text-link light" href="#contact" data-view="contact">${t('mediaCta')} <span>↗</span></a></div><div class="gallery"><div class="gallery-tile tile-a"><span>01</span><b>${t('galleryOne')}</b></div><div class="gallery-tile tile-b"><span>02</span><b>${t('galleryTwo')}</b></div><div class="gallery-tile tile-c"><span>03</span><b>${t('galleryThree')}</b></div></div></section>
  <section class="join section" id="join"><div class="join-orbit"><span>BE</span><span>JAZZY</span></div><div class="join-content"><p class="eyebrow">${t('joinKicker')}</p><h2>${t('joinTitle')}</h2><p>${t('joinText')}</p><a class="button primary" href="#contact" data-view="contact">${t('joinCta')} <span>↗</span></a></div></section>
  <section class="contact section" id="contact"><div><p class="eyebrow">${t('contact')}</p><h2><a href="mailto:vs.bejazzy@gmail.com">vs.bejazzy@gmail.com</a></h2></div><div class="contact-meta"><p>BeJazzy<br>${t('address')}</p><div class="socials"><a href="https://www.instagram.com/bejazzy_vocal_group/" target="_blank" rel="noreferrer" aria-label="Instagram" title="Instagram"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 2h10a5 5 0 0 1 5 5v10a5 5 0 0 1-5 5H7a5 5 0 0 1-5-5V7a5 5 0 0 1 5-5zm0 2a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h10a3 3 0 0 0 3-3V7a3 3 0 0 0-3-3H7zm5 3.5A5.5 5.5 0 1 1 6.5 13 5.5 5.5 0 0 1 12 7.5zm0 2A3.5 3.5 0 1 0 15.5 13 3.5 3.5 0 0 0 12 9.5zm5.25-3.25a1.25 1.25 0 1 1-1.25 1.25 1.25 1.25 0 0 1 1.25-1.25z"/></svg></a><a href="https://www.youtube.com/@bejazzyvokalnaskupina9854" target="_blank" rel="noreferrer" aria-label="YouTube" title="YouTube"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21.6 7.2a2.9 2.9 0 0 0-2-2.1C17.8 4.7 12 4.7 12 4.7s-5.8 0-7.6.4A2.9 2.9 0 0 0 2.4 7.2 29.6 29.6 0 0 0 2 12a29.6 29.6 0 0 0 .4 4.8 2.9 2.9 0 0 0 2 2.1c1.8.4 7.6.4 7.6.4s5.8 0 7.6-.4a2.9 2.9 0 0 0 2-2.1A29.6 29.6 0 0 0 22 12a29.6 29.6 0 0 0-.4-4.8zM10 15.5v-7l6 3.5-6 3.5z"/></svg></a><a href="https://www.facebook.com/vs.bejazzy" target="_blank" rel="noreferrer" aria-label="Facebook" title="Facebook"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M13.5 22v-8h2.5l.5-3h-3V7.5c0-.9.4-1.5 1.5-1.5H16V3.1c-.5-.1-1.8-.2-3.1-.2-3 0-5.1 1.8-5.1 5.1V11H5.5v3h2.3v8h5.7z"/></svg></a></div></div></section></main><footer><a class="wordmark" href="#home" data-view="home"><img class="logo" src="BeJazzy.jpg" alt="BeJazzy" /></a><p>${t('footer')}</p><button class="admin-link" data-admin>${t('admin')}</button></footer>`;
}

function adminTemplate() {
  return `<div class="admin-shell"><aside class="admin-side"><a class="wordmark" href="#" data-admin><span class="mark">B</span><span>BeJazzy<span class="dot">.</span></span></a><p class="eyebrow">CMS / 01</p><h1>${t('adminTitle')}</h1><p>${t('adminSub')}</p><div class="admin-nav"><button class="active">◷ &nbsp; ${state.lang === 'sl' ? 'Koncerti' : 'Events'}</button><button>▦ &nbsp; ${state.lang === 'sl' ? 'Strani' : 'Pages'}</button><button>◉ &nbsp; ${state.lang === 'sl' ? 'Mediji' : 'Media'}</button></div><button class="admin-exit" data-admin>← ${state.lang === 'sl' ? 'Nazaj na spletno stran' : 'Back to website'}</button></aside><section class="admin-main"><div class="admin-top"><div><span class="status-dot"></span> ${state.lang === 'sl' ? 'V živo' : 'Live'}</div><div class="admin-top-actions"><button class="lang" data-lang="${state.lang === 'sl' ? 'en' : 'sl'}">${state.lang === 'sl' ? 'EN' : 'SL'} ↗</button><button class="button primary small" data-new>${t('newEvent')} +</button></div></div><div class="admin-heading"><div><p class="eyebrow">${state.lang === 'sl' ? 'Vsebina / Koncerti' : 'Content / Events'}</p><h2>${t('adminTitle')}</h2></div><span class="count">${state.events.length} ${state.lang === 'sl' ? 'objav' : 'entries'}</span></div><div class="admin-table"><div class="table-head"><span>${t('date')}</span><span>${t('eventName')}</span><span>${t('place')}</span><span>${t('time')}</span><span></span></div>${state.events.map((event, index) => `<form class="admin-row" data-index="${index}"><input name="date" value="${event.date}" /><input name="title" value="${event.title}" /><input name="place" value="${event.place}" /><input name="time" value="${event.time}" /><div class="row-actions"><button class="save-row" title="${t('save')}">✓</button><button type="button" class="delete-row" title="Delete">×</button></div></form>`).join('')}</div><div class="admin-note">${state.lang === 'sl' ? 'Spremembe se shranijo lokalno v tem brskalniku. To je začetni CMS prototip za povezavo z dejanskim backendom.' : 'Changes are saved locally in this browser. This is a starter CMS prototype ready to connect to a real backend.'}</div></section></div>`;
}

function bind() {
  document.querySelectorAll('[data-view]').forEach(el => el.addEventListener('click', e => { e.preventDefault(); state.view = el.dataset.view; state.admin = false; render(); setTimeout(() => document.getElementById(state.view)?.scrollIntoView({ behavior: 'smooth' }), 10); }));
  document.querySelectorAll('[data-lang]').forEach(el => el.addEventListener('click', () => { state.lang = el.dataset.lang; localStorage.setItem('bejazz-lang', state.lang); render(); }));
  document.querySelectorAll('[data-admin]').forEach(el => el.addEventListener('click', () => { state.admin = !state.admin; render(); }));
  document.querySelectorAll('.admin-row').forEach(form => form.addEventListener('submit', e => { e.preventDefault(); const data = new FormData(form); state.events[form.dataset.index] = Object.fromEntries(data.entries()); persist(); form.classList.add('saved'); setTimeout(() => form.classList.remove('saved'), 700); }));
  document.querySelectorAll('.delete-row').forEach(button => button.addEventListener('click', () => { state.events.splice(button.closest('.admin-row').dataset.index, 1); persist(); render(); }));
  document.querySelector('[data-new]')?.addEventListener('click', () => { state.events.push({ date: 'DD. MM. 2026', title: state.lang === 'sl' ? 'Nov koncert' : 'New concert', place: 'City · Venue', time: '19:00', ticket: '#' }); persist(); render(); });
}
function persist() { localStorage.setItem('bejazz-events', JSON.stringify(state.events)); }
render();
